export const toolSeoKeywords: Record<string, string[]> = {
  'password-generator': [
    'password generator',
    'free password generator',
    'online password generator',
    'secure password generator',
    'random password generator',
    'strong password generator',
    'password generator online free',
    'password maker',
    'password creator',
    'generate password online',
    'create strong password',
    'random password maker',
    'secure password maker',
    'password generator tool',
    'password generator website',
    'free password maker',
    'password generator no signup',
    'browser password generator',
    'instant password generator',
    'custom password generator',
    'password generator with symbols',
    'password generator with numbers',
    'password generator uppercase lowercase',
    '16 character password generator',
    '20 character password generator',
    'long password generator',
    'complex password generator',
    'unique password generator',
    'cryptographically secure password generator',
    'password generator for accounts',
    'password generator for wifi',
    'password generator for email',
    'password generator for banking',
    'password generator for social media',
    'password generator for websites',
    'bulk password generator',
    'multiple password generator',
    'one click password generator',
    'copy password generator',
    'password generator copy paste',
    'password strength generator',
    'unbreakable password generator',
    'safe password generator',
    'reliable password generator',
    'fast password generator',
    'easy password generator',
    'simple password generator',
    'password generator app online',
    'web password generator',
    'password generator without download',
    'password generator no install',
    'password generator for students',
    'password generator for business',
    'password generator for developers',
    'password generator for teams',
    'password generator for freelancers',
    'password generator for personal use',
    'password generator for mac',
    'password generator for windows',
    'password generator for mobile',
    'password generator for chrome',
    'password generator for firefox',
    'password generator for safari',
    'password generator for linux',
    'password generator for android',
    'password generator for iphone',
    'password generator for ipad',
    'password generator for laptop',
    'password generator for desktop',
    'password generator for work',
    'password generator for home',
    'password generator for school',
    'password generator for office',
    'password generator for gaming',
    'password generator for streaming',
    'password generator for shopping',
    'password generator for cloud storage',
    'password generator for vpn',
    'password generator for router',
    'password generator for admin panel',
    'password generator for cms',
    'password generator for wordpress',
    'password generator for shopify',
    'password generator for amazon',
    'password generator for google account',
    'password generator for microsoft account',
    'password generator for apple id',
    'password generator for facebook',
    'password generator for instagram',
    'password generator for twitter',
    'password generator for linkedin',
    'password generator for github',
    'password generator for netflix',
    'password generator for paypal',
    'password generator for crypto wallet',
    'password generator for 2fa backup',
    'password generator best practice',
    'password generator security tool',
    'password generator privacy tool',
    'password generator utility',
    'password generator clypio',
    'clypio password generator',
    'best free password generator online',
    'top password generator tool',
    'trusted password generator website',
    'professional password generator',
    'high entropy password generator',
    'password generator special characters',
    'password generator adjustable length',
    'password generator customizable',
    'password generator free tool 2026',
  ],
  'typing-speed-test': [
    'typing speed test',
    'free typing speed test',
    'online typing speed test',
    'typing test online',
    'wpm test',
    'words per minute test',
    'typing speed test free',
    'typing test wpm',
    'typing accuracy test',
    'typing speed checker',
    'keyboard typing test',
    'touch typing test',
    'typing practice test',
    'typing speed test online free',
    'typing test no signup',
    'browser typing test',
    'instant typing test',
    'typing speed test tool',
    'typing speed test website',
    'typing test website',
    'free wpm test',
    'online wpm test',
    'typing speed calculator',
    'typing speed meter',
    'typing speed measurement',
    'how fast can i type',
    'check typing speed',
    'measure typing speed',
    'test typing speed online',
    'typing speed test for beginners',
    'typing speed test for students',
    'typing speed test for jobs',
    'typing speed test for data entry',
    'typing speed test for office work',
    'typing speed test for programmers',
    'typing speed test for writers',
    'typing speed test for freelancers',
    'typing speed test for interviews',
    'typing speed test for exams',
    'typing speed test for practice',
    'typing speed test with accuracy',
    'typing speed test with errors',
    'typing speed test live',
    'typing speed test real time',
    'typing speed test paragraph',
    'typing speed test random text',
    'typing speed test english',
    'typing speed test easy',
    'typing speed test medium',
    'typing speed test hard',
    'typing speed test challenge',
    'typing speed test game',
    'typing speed test competition',
    'typing speed test leaderboard',
    'typing speed test score',
    'typing speed test results',
    'typing speed test report',
    'typing speed test tracker',
    'typing speed test progress',
    'typing speed test improvement',
    'typing speed test daily',
    'typing speed test routine',
    'typing speed test training',
    'typing speed test skills',
    'typing speed test benchmark',
    'average typing speed test',
    'professional typing speed test',
    'fast typing test',
    'slow typing test',
    'typing test for mac',
    'typing test for windows',
    'typing test for mobile',
    'typing test for chrome',
    'typing test for laptop',
    'typing test for desktop',
    'typing test for work',
    'typing test for school',
    'typing test for college',
    'typing test for remote work',
    'typing test for customer support',
    'typing test for transcription',
    'typing test for content writing',
    'typing test for blogging',
    'typing test for coding',
    'typing test for notes',
    'typing test for emails',
    'typing test for chat',
    'typing test for messaging',
    'typing test for social media',
    'typing test for productivity',
    'typing test for speed building',
    'typing test for accuracy building',
    'typing test for home row',
    'typing test for touch typing',
    'typing test for keyboard skills',
    'typing test for computer skills',
    'typing test for digital literacy',
    'typing test for job application',
    'typing test for hiring',
    'typing test for assessment',
    'typing test for certification prep',
    'typing test for skill check',
    'typing test for performance',
    'typing test for efficiency',
    'typing test for workflow',
    'typing test for writers block',
    'typing test for focus',
    'typing test for concentration',
    'typing test for habit building',
    'typing test for warm up',
    'typing test for cooldown',
    'typing test for streak',
    'typing test for motivation',
    'typing speed test clypio',
    'clypio typing speed test',
    'best free typing speed test online',
    'top typing test tool',
    'trusted typing test website',
    'typing speed test utility',
    'typing speed test browser tool',
    'typing speed test no download',
    'typing speed test 2026',
  ],
  'qr-generator': [
    'qr code generator',
    'free qr code generator',
    'online qr code generator',
    'qr code maker',
    'qr code creator',
    'create qr code online',
    'generate qr code free',
    'qr code generator online',
    'qr code generator tool',
    'qr code generator website',
    'qr code generator no signup',
    'browser qr code generator',
    'instant qr code generator',
    'custom qr code generator',
    'qr code generator for url',
    'qr code generator for link',
    'qr code generator for website',
    'qr code generator for text',
    'qr code generator for email',
    'qr code generator for phone number',
    'qr code generator for wifi',
    'qr code generator for contact',
    'qr code generator for vcard',
    'qr code generator for business card',
    'qr code generator for menu',
    'qr code generator for restaurant',
    'qr code generator for cafe',
    'qr code generator for shop',
    'qr code generator for retail',
    'qr code generator for product',
    'qr code generator for packaging',
    'qr code generator for label',
    'qr code generator for poster',
    'qr code generator for flyer',
    'qr code generator for banner',
    'qr code generator for billboard',
    'qr code generator for event',
    'qr code generator for ticket',
    'qr code generator for check in',
    'qr code generator for registration',
    'qr code generator for form',
    'qr code generator for survey',
    'qr code generator for feedback',
    'qr code generator for review',
    'qr code generator for payment',
    'qr code generator for upi',
    'qr code generator for paypal',
    'qr code generator for donation',
    'qr code generator for charity',
    'qr code generator for marketing',
    'qr code generator for campaign',
    'qr code generator for social media',
    'qr code generator for instagram',
    'qr code generator for facebook',
    'qr code generator for youtube',
    'qr code generator for whatsapp',
    'qr code generator for telegram',
    'qr code generator for linkedin',
    'qr code generator for tiktok',
    'qr code generator for snapchat',
    'qr code generator for portfolio',
    'qr code generator for resume',
    'qr code generator for pdf',
    'qr code generator for document',
    'qr code generator for download',
    'qr code generator for app',
    'qr code generator for play store',
    'qr code generator for app store',
    'qr code generator for google maps',
    'qr code generator for location',
    'qr code generator for address',
    'qr code generator for hotel',
    'qr code generator for real estate',
    'qr code generator for property',
    'qr code generator for school',
    'qr code generator for classroom',
    'qr code generator for library',
    'qr code generator for museum',
    'qr code generator for exhibition',
    'qr code generator for conference',
    'qr code generator for wedding',
    'qr code generator for invitation',
    'qr code generator for gift',
    'qr code generator for coupon',
    'qr code generator for discount',
    'qr code generator for promo',
    'qr code generator for offer',
    'qr code generator for sale',
    'qr code generator for ecommerce',
    'qr code generator for store',
    'qr code generator for brand',
    'qr code generator for logo',
    'qr code generator for design',
    'qr code generator for print',
    'qr code generator for digital',
    'qr code generator for mobile',
    'qr code generator for desktop',
    'qr code generator download png',
    'qr code generator high resolution',
    'qr code generator png',
    'qr code generator image',
    'qr code generator free tool',
    'qr code generator clypio',
    'clypio qr code generator',
    'best free qr code generator online',
    'top qr code maker tool',
    'trusted qr code generator website',
    'qr code generator utility',
    'qr code generator no download',
    'qr code generator 2026',
  ],
  'short-url-generator': [
    'short url generator',
    'free short url generator',
    'online short url generator',
    'url shortener',
    'link shortener',
    'short link generator',
    'shorten url online',
    'create short url',
    'make short link',
    'url shortener free',
    'link shortener free',
    'short url maker',
    'short url creator',
    'short url tool',
    'short url website',
    'short url generator online',
    'short url generator no signup',
    'browser url shortener',
    'instant url shortener',
    'custom short url generator',
    'short url generator for social media',
    'short url generator for instagram',
    'short url generator for facebook',
    'short url generator for twitter',
    'short url generator for linkedin',
    'short url generator for youtube',
    'short url generator for tiktok',
    'short url generator for whatsapp',
    'short url generator for email',
    'short url generator for newsletter',
    'short url generator for sms',
    'short url generator for marketing',
    'short url generator for campaign',
    'short url generator for ads',
    'short url generator for affiliate',
    'short url generator for blog',
    'short url generator for website',
    'short url generator for portfolio',
    'short url generator for resume',
    'short url generator for business',
    'short url generator for shop',
    'short url generator for ecommerce',
    'short url generator for product',
    'short url generator for landing page',
    'short url generator for form',
    'short url generator for survey',
    'short url generator for event',
    'short url generator for ticket',
    'short url generator for registration',
    'short url generator for qr code',
    'short url generator for print',
    'short url generator for flyer',
    'short url generator for poster',
    'short url generator for business card',
    'short url generator for bio link',
    'short url generator for link in bio',
    'short url generator for creator',
    'short url generator for influencer',
    'short url generator for freelancer',
    'short url generator for startup',
    'short url generator for agency',
    'short url generator for brand',
    'short url generator for promotion',
    'short url generator for offer',
    'short url generator for sale',
    'short url generator for coupon',
    'short url generator for discount',
    'short url generator for tracking',
    'short url generator for analytics',
    'short url generator for click tracking',
    'short url generator for clean links',
    'short url generator for long urls',
    'short url generator for google drive',
    'short url generator for dropbox',
    'short url generator for youtube video',
    'short url generator for amazon',
    'short url generator for shopify',
    'short url generator for wordpress',
    'short url generator for github',
    'short url generator for notion',
    'short url generator for google docs',
    'short url generator for pdf',
    'short url generator for document',
    'short url generator for download',
    'short url generator for share',
    'short url generator for copy paste',
    'short url generator for mobile',
    'short url generator for desktop',
    'short url generator for chrome',
    'short url generator for mac',
    'short url generator for windows',
    'short url generator for work',
    'short url generator for school',
    'short url generator for students',
    'short url generator for teams',
    'short url generator for remote work',
    'short url generator for presentations',
    'short url generator for slides',
    'short url generator for webinars',
    'short url generator for podcast',
    'short url generator for music',
    'short url generator for video',
    'short url generator for streaming',
    'short url generator for app',
    'short url generator for store link',
    'short url generator for payment link',
    'short url generator for donation link',
    'short url generator for charity',
    'short url generator for community',
    'short url generator for forum',
    'short url generator for chat',
    'short url generator for messaging',
    'short url generator clypio',
    'clypio short url generator',
    'best free url shortener online',
    'top link shortener tool',
    'trusted short url generator website',
    'short url generator utility',
    'short url generator no download',
    'short url generator 2026',
  ],
  'markdown-formatter': [
    'markdown formatter',
    'free markdown formatter',
    'online markdown formatter',
    'markdown editor',
    'markdown preview',
    'markdown viewer',
    'markdown writer',
    'markdown tool',
    'markdown formatter online',
    'markdown formatter free',
    'markdown formatter tool',
    'markdown formatter website',
    'markdown formatter no signup',
    'browser markdown editor',
    'instant markdown preview',
    'live markdown preview',
    'markdown editor online free',
    'markdown preview online',
    'markdown formatter with preview',
    'markdown editor with preview',
    'markdown syntax formatter',
    'markdown text formatter',
    'markdown document formatter',
    'markdown note formatter',
    'markdown blog formatter',
    'markdown readme formatter',
    'markdown github formatter',
    'markdown notion formatter',
    'markdown obsidian formatter',
    'markdown stackoverflow formatter',
    'markdown devto formatter',
    'markdown jekyll formatter',
    'markdown hugo formatter',
    'markdown static site formatter',
    'markdown documentation formatter',
    'markdown api docs formatter',
    'markdown technical writing tool',
    'markdown formatting tool',
    'markdown formatting online',
    'markdown formatting helper',
    'markdown formatting checker',
    'markdown formatting validator',
    'markdown formatting preview',
    'markdown heading formatter',
    'markdown list formatter',
    'markdown table formatter',
    'markdown link formatter',
    'markdown image formatter',
    'markdown code block formatter',
    'markdown bold italic formatter',
    'markdown quote formatter',
    'markdown checklist formatter',
    'markdown task list formatter',
    'markdown syntax helper',
    'markdown syntax checker',
    'markdown syntax preview',
    'markdown syntax tutorial tool',
    'markdown learning tool',
    'markdown practice tool',
    'markdown writing tool',
    'markdown note taking tool',
    'markdown drafting tool',
    'markdown copy paste tool',
    'markdown export tool',
    'markdown html preview',
    'markdown render online',
    'markdown renderer online',
    'markdown parser online',
    'markdown converter online',
    'markdown to html preview',
    'markdown editor for students',
    'markdown editor for developers',
    'markdown editor for writers',
    'markdown editor for bloggers',
    'markdown editor for documentation',
    'markdown editor for readme',
    'markdown editor for wiki',
    'markdown editor for notes',
    'markdown editor for meetings',
    'markdown editor for reports',
    'markdown editor for projects',
    'markdown editor for teams',
    'markdown editor for freelancers',
    'markdown editor for mac',
    'markdown editor for windows',
    'markdown editor for linux',
    'markdown editor for chrome',
    'markdown editor for mobile',
    'markdown editor for laptop',
    'markdown editor for desktop',
    'markdown editor for work',
    'markdown editor for school',
    'markdown editor for college',
    'markdown editor for coding',
    'markdown editor for programming',
    'markdown editor for software docs',
    'markdown editor for api reference',
    'markdown editor for changelog',
    'markdown editor for release notes',
    'markdown editor for issue templates',
    'markdown editor for pull requests',
    'markdown editor for comments',
    'markdown editor for forums',
    'markdown editor for reddit',
    'markdown editor for discord',
    'markdown editor for slack',
    'markdown editor for email drafts',
    'markdown editor for content marketing',
    'markdown editor for seo content',
    'markdown editor for landing pages',
    'markdown editor for product docs',
    'markdown editor for help center',
    'markdown editor for knowledge base',
    'markdown editor for tutorials',
    'markdown editor for guides',
    'markdown editor for how to articles',
    'markdown formatter clypio',
    'clypio markdown formatter',
    'best free markdown formatter online',
    'top markdown editor tool',
    'trusted markdown formatter website',
    'markdown formatter utility',
    'markdown formatter no download',
    'markdown formatter 2026',
  ],
  'stopwatch': [
    'online stopwatch',
    'free online stopwatch',
    'stopwatch online',
    'stopwatch timer',
    'digital stopwatch',
    'precision stopwatch',
    'stopwatch with laps',
    'lap stopwatch',
    'stopwatch tool',
    'stopwatch website',
    'stopwatch online free',
    'stopwatch no signup',
    'browser stopwatch',
    'instant stopwatch',
    'web stopwatch',
    'stopwatch for work',
    'stopwatch for study',
    'stopwatch for exams',
    'stopwatch for practice',
    'stopwatch for sports',
    'stopwatch for running',
    'stopwatch for workout',
    'stopwatch for gym',
    'stopwatch for training',
    'stopwatch for coaching',
    'stopwatch for athletes',
    'stopwatch for swimming',
    'stopwatch for cycling',
    'stopwatch for track',
    'stopwatch for intervals',
    'stopwatch for hiit',
    'stopwatch for crossfit',
    'stopwatch for yoga',
    'stopwatch for meditation',
    'stopwatch for breathing',
    'stopwatch for pomodoro',
    'stopwatch for focus',
    'stopwatch for productivity',
    'stopwatch for time blocking',
    'stopwatch for meetings',
    'stopwatch for presentations',
    'stopwatch for speeches',
    'stopwatch for debates',
    'stopwatch for cooking',
    'stopwatch for baking',
    'stopwatch for recipes',
    'stopwatch for kitchen',
    'stopwatch for lab',
    'stopwatch for experiments',
    'stopwatch for science',
    'stopwatch for classroom',
    'stopwatch for teachers',
    'stopwatch for students',
    'stopwatch for kids',
    'stopwatch for games',
    'stopwatch for challenges',
    'stopwatch for competitions',
    'stopwatch for events',
    'stopwatch for races',
    'stopwatch for lap times',
    'stopwatch for split times',
    'stopwatch for milliseconds',
    'stopwatch for accurate timing',
    'stopwatch for precise timing',
    'stopwatch for elapsed time',
    'stopwatch for duration',
    'stopwatch for countdown companion',
    'stopwatch for task timing',
    'stopwatch for project timing',
    'stopwatch for freelance billing',
    'stopwatch for time tracking',
    'stopwatch for workflow',
    'stopwatch for daily routine',
    'stopwatch for habit tracking',
    'stopwatch for speed test',
    'stopwatch for reaction time',
    'stopwatch for drills',
    'stopwatch for reps',
    'stopwatch for sets',
    'stopwatch for rest periods',
    'stopwatch for recovery',
    'stopwatch for warm up',
    'stopwatch for cooldown',
    'stopwatch for mac',
    'stopwatch for windows',
    'stopwatch for chrome',
    'stopwatch for mobile',
    'stopwatch for iphone',
    'stopwatch for android',
    'stopwatch for ipad',
    'stopwatch for laptop',
    'stopwatch for desktop',
    'stopwatch for remote work',
    'stopwatch for office',
    'stopwatch for warehouse',
    'stopwatch for manufacturing',
    'stopwatch for assembly line',
    'stopwatch for quality check',
    'stopwatch for service timing',
    'stopwatch for customer support',
    'stopwatch for call timing',
    'stopwatch for interview practice',
    'stopwatch for public speaking',
    'stopwatch for music practice',
    'stopwatch for instrument practice',
    'stopwatch for dance practice',
    'stopwatch for art sessions',
    'stopwatch for reading sessions',
    'stopwatch for writing sessions',
    'stopwatch clypio',
    'clypio stopwatch',
    'best free online stopwatch',
    'top stopwatch tool',
    'trusted stopwatch website',
    'stopwatch utility',
    'stopwatch no download',
    'stopwatch 2026',
  ],
  'unit-converter': [
    'unit converter',
    'free unit converter',
    'online unit converter',
    'unit conversion tool',
    'unit conversion calculator',
    'measurement converter',
    'convert units online',
    'unit converter online free',
    'unit converter tool',
    'unit converter website',
    'unit converter no signup',
    'browser unit converter',
    'instant unit converter',
    'length converter',
    'weight converter',
    'temperature converter',
    'volume converter',
    'area converter',
    'speed converter',
    'distance converter',
    'height converter',
    'mass converter',
    'metric converter',
    'imperial converter',
    'metric to imperial converter',
    'imperial to metric converter',
    'meters to feet converter',
    'feet to meters converter',
    'kilometers to miles converter',
    'miles to kilometers converter',
    'centimeters to inches converter',
    'inches to centimeters converter',
    'kilograms to pounds converter',
    'pounds to kilograms converter',
    'grams to ounces converter',
    'ounces to grams converter',
    'celsius to fahrenheit converter',
    'fahrenheit to celsius converter',
    'liters to gallons converter',
    'gallons to liters converter',
    'milliliters to cups converter',
    'cups to milliliters converter',
    'unit converter for students',
    'unit converter for school',
    'unit converter for homework',
    'unit converter for physics',
    'unit converter for chemistry',
    'unit converter for math',
    'unit converter for engineering',
    'unit converter for science',
    'unit converter for construction',
    'unit converter for architecture',
    'unit converter for cooking',
    'unit converter for baking',
    'unit converter for recipes',
    'unit converter for kitchen',
    'unit converter for travel',
    'unit converter for road trip',
    'unit converter for fuel',
    'unit converter for weather',
    'unit converter for fitness',
    'unit converter for health',
    'unit converter for body weight',
    'unit converter for height measurement',
    'unit converter for shopping',
    'unit converter for online shopping',
    'unit converter for import products',
    'unit converter for international',
    'unit converter for usa',
    'unit converter for uk',
    'unit converter for europe',
    'unit converter for canada',
    'unit converter for australia',
    'unit converter for india',
    'unit converter for asia',
    'unit converter for global trade',
    'unit converter for business',
    'unit converter for logistics',
    'unit converter for shipping',
    'unit converter for warehouse',
    'unit converter for manufacturing',
    'unit converter for diy',
    'unit converter for home improvement',
    'unit converter for real estate',
    'unit converter for land measurement',
    'unit converter for room size',
    'unit converter for furniture',
    'unit converter for tv size',
    'unit converter for screen size',
    'unit converter for clothing size',
    'unit converter for shoes',
    'unit converter for jewelry',
    'unit converter for gold weight',
    'unit converter for silver weight',
    'unit converter for medicine dosing reference',
    'unit converter for lab measurements',
    'unit converter for data sheets',
    'unit converter for blueprints',
    'unit converter for maps',
    'unit converter for gps distance',
    'unit converter for aviation reference',
    'unit converter for marine reference',
    'unit converter for automotive',
    'unit converter for tire pressure reference',
    'unit converter for speed limits',
    'unit converter for mac',
    'unit converter for windows',
    'unit converter for mobile',
    'unit converter for chrome',
    'unit converter for laptop',
    'unit converter for desktop',
    'unit converter for work',
    'unit converter for office',
    'unit converter for remote work',
    'unit converter for freelancers',
    'unit converter for quick reference',
    'unit converter for daily life',
    'unit converter for everyday use',
    'unit converter clypio',
    'clypio unit converter',
    'best free unit converter online',
    'top unit conversion tool',
    'trusted unit converter website',
    'unit converter utility',
    'unit converter no download',
    'unit converter 2026',
  ],
  'todo-list': [
    'online todo list',
    'free online todo list',
    'todo list online',
    'to do list online',
    'task list online',
    'online task manager',
    'todo list tool',
    'todo list website',
    'todo list app online',
    'todo list no signup',
    'browser todo list',
    'instant todo list',
    'simple todo list',
    'easy todo list',
    'daily todo list',
    'personal todo list',
    'work todo list',
    'student todo list',
    'office todo list',
    'home todo list',
    'family todo list',
    'shopping todo list',
    'grocery todo list',
    'chore todo list',
    'project todo list',
    'team todo list',
    'freelancer todo list',
    'remote work todo list',
    'startup todo list',
    'business todo list',
    'weekly todo list',
    'monthly todo list',
    'daily planner todo list',
    'checklist online',
    'online checklist',
    'free checklist tool',
    'task checklist',
    'priority todo list',
    'urgent task list',
    'important task list',
    'productivity todo list',
    'focus todo list',
    'goal todo list',
    'habit todo list',
    'routine todo list',
    'morning todo list',
    'evening todo list',
    'study todo list',
    'exam todo list',
    'homework todo list',
    'assignment todo list',
    'college todo list',
    'school todo list',
    'teacher todo list',
    'classroom todo list',
    'meeting todo list',
    'agenda todo list',
    'event planning todo list',
    'wedding todo list',
    'travel todo list',
    'packing todo list',
    'moving todo list',
    'renovation todo list',
    'cleaning todo list',
    'maintenance todo list',
    'errand todo list',
    'appointment todo list',
    'reminder todo list',
    'deadline todo list',
    'milestone todo list',
    'sprint todo list',
    'kanban style todo list',
    'minimal todo list',
    'lightweight todo list',
    'no account todo list',
    'no login todo list',
    'private todo list',
    'browser based todo list',
    'web todo list',
    'todo list for mac',
    'todo list for windows',
    'todo list for chrome',
    'todo list for mobile',
    'todo list for iphone',
    'todo list for android',
    'todo list for ipad',
    'todo list for laptop',
    'todo list for desktop',
    'todo list for productivity',
    'todo list for time management',
    'todo list for organization',
    'todo list for planning',
    'todo list for scheduling',
    'todo list for prioritization',
    'todo list for workflow',
    'todo list for side projects',
    'todo list for coding tasks',
    'todo list for writing tasks',
    'todo list for content creation',
    'todo list for marketing tasks',
    'todo list for sales tasks',
    'todo list for support tasks',
    'todo list for admin tasks',
    'todo list for bookkeeping tasks',
    'todo list for client work',
    'todo list for job search',
    'todo list for interview prep',
    'todo list for resume tasks',
    'todo list for application tracking',
    'todo list for personal goals',
    'todo list for fitness goals',
    'todo list for health goals',
    'todo list for self improvement',
    'todo list for mindfulness',
    'todo list for journaling companion',
    'todo list for note taking companion',
    'todo list for brainstorming',
    'todo list for ideas',
    'todo list for quick capture',
    'todo list for daily review',
    'todo list for weekly review',
    'todo list clypio',
    'clypio todo list',
    'best free online todo list',
    'top task list tool',
    'trusted todo list website',
    'todo list utility',
    'todo list no download',
    'todo list 2026',
  ],
  'bmi-calculator': [
    'bmi calculator',
    'free bmi calculator',
    'online bmi calculator',
    'body mass index calculator',
    'bmi calculator online',
    'bmi calculator free',
    'bmi calculator tool',
    'bmi calculator website',
    'bmi calculator no signup',
    'browser bmi calculator',
    'instant bmi calculator',
    'bmi check online',
    'calculate bmi online',
    'bmi score calculator',
    'bmi index calculator',
    'bmi measurement calculator',
    'bmi calculator for adults',
    'bmi calculator for men',
    'bmi calculator for women',
    'bmi calculator for teens reference',
    'bmi calculator for fitness',
    'bmi calculator for weight loss',
    'bmi calculator for health',
    'bmi calculator for wellness',
    'bmi calculator for diet planning',
    'bmi calculator for gym',
    'bmi calculator for workout planning',
    'bmi calculator for nutrition',
    'bmi calculator for body weight',
    'bmi calculator for height and weight',
    'bmi calculator metric',
    'bmi calculator imperial',
    'bmi calculator kg cm',
    'bmi calculator lbs feet',
    'bmi calculator pounds inches',
    'bmi calculator kilograms meters',
    'bmi calculator cm kg',
    'bmi calculator feet lbs',
    'bmi category calculator',
    'underweight bmi calculator',
    'normal bmi calculator',
    'overweight bmi calculator',
    'obesity bmi calculator',
    'healthy weight calculator',
    'weight status calculator',
    'body weight index calculator',
    'bmi chart calculator',
    'bmi range calculator',
    'bmi result calculator',
    'bmi checker tool',
    'bmi screening tool',
    'bmi health calculator',
    'bmi wellness tool',
    'bmi tracking calculator',
    'bmi progress calculator',
    'bmi trend calculator',
    'bmi goal calculator',
    'bmi comparison calculator',
    'bmi calculator for students',
    'bmi calculator for school project',
    'bmi calculator for health class',
    'bmi calculator for nursing reference',
    'bmi calculator for medical students reference',
    'bmi calculator for personal use',
    'bmi calculator for home',
    'bmi calculator for family',
    'bmi calculator for parents',
    'bmi calculator for athletes reference',
    'bmi calculator for runners',
    'bmi calculator for bodybuilding reference',
    'bmi calculator for yoga',
    'bmi calculator for pilates',
    'bmi calculator for walking plan',
    'bmi calculator for running plan',
    'bmi calculator for calorie planning reference',
    'bmi calculator for lifestyle change',
    'bmi calculator for healthy living',
    'bmi calculator for weight management',
    'bmi calculator for obesity awareness',
    'bmi calculator for health screening',
    'bmi calculator for doctor visit prep',
    'bmi calculator for checkup prep',
    'bmi calculator for insurance form reference',
    'bmi calculator for fitness app companion',
    'bmi calculator for smart scale companion',
    'bmi calculator for wearable data reference',
    'bmi calculator for mac',
    'bmi calculator for windows',
    'bmi calculator for mobile',
    'bmi calculator for iphone',
    'bmi calculator for android',
    'bmi calculator for ipad',
    'bmi calculator for chrome',
    'bmi calculator for laptop',
    'bmi calculator for desktop',
    'bmi calculator for work wellness',
    'bmi calculator for office health',
    'bmi calculator for remote workers',
    'bmi calculator for quick check',
    'bmi calculator for daily health',
    'bmi calculator for monthly tracking',
    'bmi calculator for quarterly tracking',
    'bmi calculator for new year goals',
    'bmi calculator for summer fitness',
    'bmi calculator for winter health',
    'bmi calculator for postpartum reference',
    'bmi calculator for senior health reference',
    'bmi calculator for pregnancy reference note',
    'bmi calculator for height conversion',
    'bmi calculator for weight conversion',
    'bmi calculator with categories',
    'bmi calculator with explanation',
    'bmi calculator educational tool',
    'bmi calculator informative tool',
    'bmi calculator clypio',
    'clypio bmi calculator',
    'best free bmi calculator online',
    'top bmi calculator tool',
    'trusted bmi calculator website',
    'bmi calculator utility',
    'bmi calculator no download',
    'bmi calculator 2026',
  ],
};

export function getToolKeywords(slug: string): string[] {
  return (toolSeoKeywords[slug] ?? []).slice(0, 100);
}
